Update pipeline

diff --git a/.github/workflows/mlsecops.yaml b/.github/workflows/mlsecops.yaml
--- a/.github/workflows/mlsecops.yaml
+++ b/.github/workflows/mlsecops.yaml
@@ -106,11 +106,10 @@ jobs:
 
     - name: Sign Model with Cosign
       env:
-        COSIGN_EXPERIMENTAL: 0
         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
       run: |
         echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
-        cosign sign-blob --key cosign.key --output-signature model/cnn_model.pt.sig model/cnn_model.pt || { echo "Signing failed"; cat cosign.key; exit 1; }
+        cosign sign-blob --key cosign.key --output-signature model/cnn_model.pt.sig --tlog-upload=false model/cnn_model.pt || { echo "Signing failed"; cat cosign.key; exit 1; }
         cosign public-key --key cosign.key > cosign.pub
         rm cosign.key
 
