Update pipeline

diff --git a/.github/workflows/mlsecops.yaml b/.github/workflows/mlsecops.yaml
--- a/.github/workflows/mlsecops.yaml
+++ b/.github/workflows/mlsecops.yaml
@@ -98,7 +98,7 @@ jobs:
 
     - name: Set up Cosign
       run: |
-        COSIGN_VERSION=v2.2.1
+        COSIGN_VERSION=v2.2.2
         curl -LO https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64
         chmod +x cosign-linux-amd64
         sudo mv cosign-linux-amd64 /usr/local/bin/cosign
@@ -109,7 +109,7 @@ jobs:
         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
       run: |
         echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
-        cosign sign-blob --key cosign.key --output-signature model/cnn_model.pt.sig --tlog-upload=false model/cnn_model.pt || { echo "Signing failed"; cat cosign.key; exit 1; }
+        cosign sign-blob --key cosign.key --output-signature model/cnn_model.pt.sig model/cnn_model.pt || { echo "Signing failed"; cat cosign.key; exit 1; }
         cosign public-key --key cosign.key > cosign.pub
         rm cosign.key
 
@@ -127,5 +127,5 @@ jobs:
 
     - name: Verify Cosign Signature
       run: |
-        cosign verify-blob --key cosign.pub --signature model/cnn_model.pt.sig --tlog-upload=false model/cnn_model.pt || { echo "Verification failed"; cat cosign.pub; exit 1; }
+        cosign verify-blob --key cosign.pub --signature model/cnn_model.pt.sig model/cnn_model.pt || { echo "Verification failed"; cat cosign.pub; exit 1; }
         rm cosign.pub
